import type { Metadata } from "next";
import { Inter, Geologica, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin", "cyrillic"],
});

const titleFont = Geologica({
  variable: "--font-title",
  subsets: ["latin", "cyrillic"],
});

const monoFont = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontVariables = `${sans.variable} ${titleFont.variable} ${monoFont.variable}`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta />
      </Head>
      <body className={`${fontVariables}`}>{children}</body>
    </html>
  );
}
