import type { Metadata } from "next";
import { Inter, Geologica } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin", "cyrillic"],
});

const titleFont = Geologica({
  variable: "--font-title",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta />
      </Head>
      <body className={`${sans.variable} ${titleFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
